#cloud-config

runcmd:
    - [ wget, "github.com"]

write_file:
- content: |
    [Unit]
    Description=EC2 termination handler

    [Service]
    ExecStart=/usr/local/bin/ec2-termination-handler-rust

    [Install]
    WantedBy=multi-user.target
  path: /etc/systemd/system/ec2-termination-handler.service
  permissions: '0755'
