#cloud-config

runcmd:
    - [ wget, "github.com"]

write_file:
- content: |
    [Unit]
    Description=EC2 termination handler

    [Service]
    ExecStart=/usr/local/bin/ec2-termination-handler-rust

    [Install]
    WantedBy=multi-user.target
  path: /etc/systemd/system/ec2-termination-handler.service
  permissions: '0755'

apt:
  sources:
    fluentbit:
      source: "deb [signed-by=$KEY_FILE] https://packages.fluentbit.io/ubuntu/jammy jammy main"
      keyid: C3C0A28534B9293EAF51FABD9F9DDC083888C1CD
package_update: true
package_upgrade: true

write_files:
  - path: /etc/fluent-bit/fluent-bit.conf
    content: |
      [SERVICE]
        http_server on
        http_listen 0.0.0.0
        http_port 2020
      [INPUT]
        name http
        listen 0.0.0.0
        port 8888

packages:
  - fluent-bit

runcmd:
  - systemctl start fluent-bit
